/*
 * AI-generated test file.
 *
 * Disclaimer:
 * This test code was generated by AI and should be reviewed by a human before
 * relying on it for grading, production, or benchmarking decisions.
 */

#include "utils/arraylist.h"

#include <assert.h>
#include <stdio.h>
#include <time.h>

typedef struct TestStruct {
    int id;
    double value;
} TestStruct;

static double nowSeconds(void) {
    return (double)clock() / (double)CLOCKS_PER_SEC;
}

static void printTiming(const char* label, double seconds) {
    printf("%s: %.6f seconds\n", label, seconds);
}

static void testInit(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 1);

    assert(list != nullptr);
    assert(ArrayListGetLength(list) == 0);
    assert(ArrayListGetCapacity(list) == 1);
    assert(ArrayListGetElementSize(list) == sizeof(int));
    assert(ArrayListAt(list, 0) == nullptr);

    arrayListFree(list);
}

static void testInitWithLargerCapacity(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 8);

    assert(list != nullptr);
    assert(ArrayListGetLength(list) == 0);
    assert(ArrayListGetCapacity(list) == 8);
    assert(ArrayListGetElementSize(list) == sizeof(int));
    assert(ArrayListAt(list, 0) == nullptr);

    arrayListFree(list);
}

static void testGettersOnNull(void) {
    assert(ArrayListGetLength(nullptr) == -1);
    assert(ArrayListGetCapacity(nullptr) == 0);
    assert(ArrayListGetElementSize(nullptr) == 0);
    assert(ArrayListAt(nullptr, 0) == nullptr);
}

static void testGetOnEmptyListReturnsNull(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 1);

    assert(list != nullptr);
    assert(ArrayListAt(list, 0) == nullptr);
    assert(ArrayListAt(list, -1) == nullptr);

    arrayListFree(list);
}

static void testAppendSingleInt(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 1);
    assert(list != nullptr);

    int value = 42;
    arrayListAppend(list, &value);

    assert(ArrayListGetLength(list) == 1);
    assert(ArrayListGetCapacity(list) >= 1);

    int* storedValue = (int*)ArrayListAt(list, 0);
    assert(storedValue != nullptr);
    assert(*storedValue == 42);

    arrayListFree(list);
}

static void testAppendMultipleInts(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 1);
    assert(list != nullptr);

    unsigned int previousCapacity = ArrayListGetCapacity(list);

    for (int i = 0; i < 10; i++) {
        arrayListAppend(list, &i);
        assert(ArrayListGetLength(list) == i + 1);
        assert(ArrayListGetCapacity(list) >= (unsigned int)ArrayListGetLength(list));

        unsigned int currentCapacity = ArrayListGetCapacity(list);
        if (currentCapacity != previousCapacity) {
            assert(currentCapacity > previousCapacity);
            previousCapacity = currentCapacity;
        }
    }

    assert(ArrayListGetLength(list) == 10);

    for (int i = 0; i < 10; i++) {
        int* storedValue = (int*)ArrayListAt(list, i);
        assert(storedValue != nullptr);
        assert(*storedValue == i);
    }

    arrayListFree(list);
}

static void testCapacityGrowsWhenNeeded(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 2);
    assert(list != nullptr);
    assert(ArrayListGetCapacity(list) == 2);

    int a = 1;
    int b = 2;
    int c = 3;

    arrayListAppend(list, &a);
    arrayListAppend(list, &b);

    assert(ArrayListGetLength(list) == 2);
    assert(ArrayListGetCapacity(list) >= 2);

    unsigned int capacityBeforeGrowth = ArrayListGetCapacity(list);

    arrayListAppend(list, &c);

    assert(ArrayListGetLength(list) == 3);
    assert(ArrayListGetCapacity(list) >= 3);
    assert(ArrayListGetCapacity(list) >= capacityBeforeGrowth);

    assert(*(int*)ArrayListAt(list, 0) == 1);
    assert(*(int*)ArrayListAt(list, 1) == 2);
    assert(*(int*)ArrayListAt(list, 2) == 3);

    arrayListFree(list);
}

static void testAppendCopiesValue(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 1);
    assert(list != nullptr);

    int value = 5;
    arrayListAppend(list, &value);

    value = 999;

    int* storedValue = (int*)ArrayListAt(list, 0);
    assert(storedValue != nullptr);
    assert(*storedValue == 5);

    arrayListFree(list);
}

static void testAtBadIndexesReturnNull(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 1);
    assert(list != nullptr);

    int a = 10;
    int b = 20;
    arrayListAppend(list, &a);
    arrayListAppend(list, &b);

    assert(ArrayListAt(list, -1) == nullptr);
    assert(ArrayListAt(list, 2) == nullptr);
    assert(ArrayListAt(list, 999) == nullptr);

    arrayListFree(list);
}

static void testPopOnEmptyDoesNothing(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 4);
    assert(list != nullptr);

    arrayListPop(list);

    assert(ArrayListGetLength(list) == 0);
    assert(ArrayListGetCapacity(list) == 4);
    assert(ArrayListAt(list, 0) == nullptr);

    arrayListFree(list);
}

static void testPopSingleElement(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 1);
    assert(list != nullptr);

    int value = 77;
    arrayListAppend(list, &value);

    assert(ArrayListGetLength(list) == 1);

    arrayListPop(list);

    assert(ArrayListGetLength(list) == 0);
    assert(ArrayListAt(list, 0) == nullptr);

    arrayListFree(list);
}

static void testPopMultipleElements(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 1);
    assert(list != nullptr);

    int a = 11;
    int b = 22;
    int c = 33;

    arrayListAppend(list, &a);
    arrayListAppend(list, &b);
    arrayListAppend(list, &c);

    assert(ArrayListGetLength(list) == 3);

    arrayListPop(list);

    assert(ArrayListGetLength(list) == 2);

    int* first = (int*)ArrayListAt(list, 0);
    int* second = (int*)ArrayListAt(list, 1);

    assert(first != nullptr);
    assert(second != nullptr);
    assert(*first == 11);
    assert(*second == 22);
    assert(ArrayListAt(list, 2) == nullptr);

    arrayListFree(list);
}

static void testPopPreservesEarlierValues(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 2);
    assert(list != nullptr);

    int a = 1;
    int b = 2;
    int c = 3;
    int d = 4;

    arrayListAppend(list, &a);
    arrayListAppend(list, &b);
    arrayListAppend(list, &c);
    arrayListAppend(list, &d);

    arrayListPop(list);
    arrayListPop(list);

    assert(ArrayListGetLength(list) == 2);
    assert(*(int*)ArrayListAt(list, 0) == 1);
    assert(*(int*)ArrayListAt(list, 1) == 2);
    assert(ArrayListAt(list, 2) == nullptr);

    arrayListFree(list);
}

static void testAppendStructs(void) {
    ArrayList* list = ArrayListInit(sizeof(TestStruct), 1);
    assert(list != nullptr);

    TestStruct a = {1, 1.5};
    TestStruct b = {2, 3.25};
    TestStruct c = {3, 9.75};

    arrayListAppend(list, &a);
    arrayListAppend(list, &b);
    arrayListAppend(list, &c);

    assert(ArrayListGetLength(list) == 3);
    assert(ArrayListGetCapacity(list) >= 3);

    TestStruct* first = (TestStruct*)ArrayListAt(list, 0);
    TestStruct* second = (TestStruct*)ArrayListAt(list, 1);
    TestStruct* third = (TestStruct*)ArrayListAt(list, 2);

    assert(first != nullptr);
    assert(second != nullptr);
    assert(third != nullptr);

    assert(first->id == 1);
    assert(first->value == 1.5);

    assert(second->id == 2);
    assert(second->value == 3.25);

    assert(third->id == 3);
    assert(third->value == 9.75);

    arrayListFree(list);
}

static void testStructCopyIsIndependent(void) {
    ArrayList* list = ArrayListInit(sizeof(TestStruct), 1);
    assert(list != nullptr);

    TestStruct item = {10, 2.0};
    arrayListAppend(list, &item);

    item.id = 999;
    item.value = 123.456;

    TestStruct* stored = (TestStruct*)ArrayListAt(list, 0);
    assert(stored != nullptr);
    assert(stored->id == 10);
    assert(stored->value == 2.0);

    arrayListFree(list);
}

static void testClearResetsLengthAndCapacity(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 2);
    assert(list != nullptr);

    int a = 1;
    int b = 2;
    int c = 3;

    arrayListAppend(list, &a);
    arrayListAppend(list, &b);
    arrayListAppend(list, &c);

    assert(ArrayListGetLength(list) == 3);

    arrayListClear(list, 5);

    assert(ArrayListGetLength(list) == 0);
    assert(ArrayListGetCapacity(list) == 5);
    assert(ArrayListGetElementSize(list) == sizeof(int));
    assert(ArrayListAt(list, 0) == nullptr);

    arrayListFree(list);
}

static void testClearThenAppendAgain(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 2);
    assert(list != nullptr);

    int a = 10;
    int b = 20;
    int c = 30;

    arrayListAppend(list, &a);
    arrayListAppend(list, &b);

    arrayListClear(list, 4);

    assert(ArrayListGetLength(list) == 0);
    assert(ArrayListGetCapacity(list) == 4);

    arrayListAppend(list, &c);

    assert(ArrayListGetLength(list) == 1);
    assert(*(int*)ArrayListAt(list, 0) == 30);

    arrayListFree(list);
}

static void testClearEmptyList(void) {
    ArrayList* list = ArrayListInit(sizeof(int), 3);
    assert(list != nullptr);

    arrayListClear(list, 7);

    assert(ArrayListGetLength(list) == 0);
    assert(ArrayListGetCapacity(list) == 7);
    assert(ArrayListAt(list, 0) == nullptr);

    arrayListFree(list);
}

static void testPerformanceAppend(size_t count) {
    ArrayList* list = ArrayListInit(sizeof(int), 1);
    assert(list != nullptr);

    double start = nowSeconds();

    for (size_t i = 0; i < count; i++) {
        int value = (int)i;
        arrayListAppend(list, &value);
    }

    double end = nowSeconds();

    assert(ArrayListGetLength(list) == (int)count);
    assert(ArrayListGetCapacity(list) >= count);

    printTiming("Performance - append", end - start);

    arrayListFree(list);
}

static void testPerformanceAt(size_t count) {
    ArrayList* list = ArrayListInit(sizeof(int), (unsigned int)count);
    assert(list != nullptr);

    for (size_t i = 0; i < count; i++) {
        int value = (int)i;
        arrayListAppend(list, &value);
    }

    volatile long long sum = 0;
    double start = nowSeconds();

    for (size_t i = 0; i < count; i++) {
        int* value = (int*)ArrayListAt(list, (int)i);
        assert(value != nullptr);
        sum += *value;
    }

    double end = nowSeconds();

    printTiming("Performance - at", end - start);

    if (sum == -1) {
        printf("Impossible sum: %lld\n", sum);
    }

    arrayListFree(list);
}

static void testPerformancePop(size_t count) {
    ArrayList* list = ArrayListInit(sizeof(int), (unsigned int)count);
    assert(list != nullptr);

    for (size_t i = 0; i < count; i++) {
        int value = (int)i;
        arrayListAppend(list, &value);
    }

    double start = nowSeconds();

    while (ArrayListGetLength(list) > 0) {
        arrayListPop(list);
    }

    double end = nowSeconds();

    assert(ArrayListGetLength(list) == 0);
    printTiming("Performance - pop", end - start);

    arrayListFree(list);
}

static void testPerformanceClear(size_t count) {
    ArrayList* list = ArrayListInit(sizeof(int), 1);
    assert(list != nullptr);

    for (size_t i = 0; i < count; i++) {
        int value = (int)i;
        arrayListAppend(list, &value);
    }

    double start = nowSeconds();
    arrayListClear(list, 16);
    double end = nowSeconds();

    assert(ArrayListGetLength(list) == 0);
    assert(ArrayListGetCapacity(list) == 16);

    printTiming("Performance - clear", end - start);

    arrayListFree(list);
}

int main(void) {
    testInit();
    testInitWithLargerCapacity();
    testGettersOnNull();
    testGetOnEmptyListReturnsNull();
    testAppendSingleInt();
    testAppendMultipleInts();
    testCapacityGrowsWhenNeeded();
    testAppendCopiesValue();
    testAtBadIndexesReturnNull();
    testPopOnEmptyDoesNothing();
    testPopSingleElement();
    testPopMultipleElements();
    testPopPreservesEarlierValues();
    testAppendStructs();
    testStructCopyIsIndependent();
    testClearResetsLengthAndCapacity();
    testClearThenAppendAgain();
    testClearEmptyList();

    printf("All ArrayList correctness tests passed.\n\n");

    testPerformanceAppend(100000);
    testPerformanceAt(100000);
    testPerformancePop(100000);
    testPerformanceClear(100000);

    return 0;
}