CMAKE_MINIMUM_REQUIRED(VERSION 3.10)
PROJECT(RTS)

SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)

IF(APPLE)
    LIST(APPEND CMAKE_PREFIX_PATH "/opt/homebrew")
ENDIF()

FIND_PACKAGE(raylib CONFIG REQUIRED)

ADD_EXECUTABLE(main "./main.c")
SET_PROPERTY(TARGET main PROPERTY C_STANDARD 23)

ADD_LIBRARY(grid STATIC "src/utils/grid.c")
SET_PROPERTY(TARGET grid PROPERTY C_STANDARD 23)

ADD_LIBRARY(arraylist STATIC "src/utils/arraylist.c"
        include/arraylist.h)
SET_PROPERTY(TARGET arraylist PROPERTY C_STANDARD 23)

TARGET_INCLUDE_DIRECTORIES(main PRIVATE "./include")
TARGET_INCLUDE_DIRECTORIES(grid PRIVATE "./include")
TARGET_INCLUDE_DIRECTORIES(arraylist PRIVATE "./include")

TARGET_LINK_LIBRARIES(grid PUBLIC raylib)
TARGET_LINK_LIBRARIES(main PRIVATE grid arraylist)
